/**
 * StatStack — Statistics Database
 * 365+ curated statistic pairs for daily challenges.
 * Each day uses 10 pairs from this pool, selected deterministically by date.
 *
 * Format: { text: "description", value: number, unit: "unit", source: "source" }
 */
const STATS_DATABASE = [
  { text: "Population of Tokyo metro area", value: 37400000, unit: "people", source: "UN 2023" },
  { text: "Population of New York City metro area", value: 20100000, unit: "people", source: "US Census 2023" },
  { text: "Population of London metro area", value: 14800000, unit: "people", source: "ONS 2023" },
  { text: "Population of Mumbai metro area", value: 21700000, unit: "people", source: "UN 2023" },
  { text: "Population of São Paulo metro area", value: 22400000, unit: "people", source: "IBGE 2023" },
  { text: "Population of Cairo metro area", value: 22200000, unit: "people", source: "UN 2023" },
  { text: "Population of Mexico City metro area", value: 21800000, unit: "people", source: "INEGI 2023" },
  { text: "Population of Shanghai metro area", value: 29200000, unit: "people", source: "NBS China 2023" },
  { text: "Population of Lagos metro area", value: 16600000, unit: "people", source: "UN 2023" },
  { text: "Population of Jakarta metro area", value: 35400000, unit: "people", source: "BPS 2023" },
  { text: "Distance from Earth to the Moon", value: 384400, unit: "km", source: "NASA" },
  { text: "Distance from Earth to the Sun", value: 149600000, unit: "km", source: "NASA" },
  { text: "Distance from Earth to Mars (closest)", value: 54600000, unit: "km", source: "NASA" },
  { text: "Diameter of Earth", value: 12742, unit: "km", source: "NASA" },
  { text: "Diameter of Jupiter", value: 139820, unit: "km", source: "NASA" },
  { text: "Diameter of the Sun", value: 1392700, unit: "km", source: "NASA" },
  { text: "Speed of light", value: 299792, unit: "km/s", source: "NIST" },
  { text: "Speed of sound in air", value: 343, unit: "m/s", source: "Physics" },
  { text: "Height of Mount Everest", value: 8849, unit: "meters", source: "Nepal Survey 2020" },
  { text: "Height of Mount Kilimanjaro", value: 5895, unit: "meters", source: "Tanzania Survey" },
  { text: "Height of Mount Fuji", value: 3776, unit: "meters", source: "GSI Japan" },
  { text: "Height of the Eiffel Tower", value: 330, unit: "meters", source: "SETE" },
  { text: "Height of the Burj Khalifa", value: 828, unit: "meters", source: "Emaar" },
  { text: "Height of the Empire State Building", value: 443, unit: "meters", source: "ESRT" },
  { text: "Height of the Statue of Liberty (with pedestal)", value: 93, unit: "meters", source: "NPS" },
  { text: "Depth of the Mariana Trench", value: 10994, unit: "meters", source: "NOAA" },
  { text: "Average depth of the ocean", value: 3688, unit: "meters", source: "NOAA" },
  { text: "Length of the Great Wall of China", value: 21196, unit: "km", source: "SACH 2012" },
  { text: "Length of the Nile River", value: 6650, unit: "km", source: "Various" },
  { text: "Length of the Amazon River", value: 6400, unit: "km", source: "INPE" },
  { text: "Length of the Mississippi River", value: 3766, unit: "km", source: "USGS" },
  { text: "Area of Russia", value: 17098242, unit: "km²", source: "UN" },
  { text: "Area of Canada", value: 9984670, unit: "km²", source: "StatsCan" },
  { text: "Area of the United States", value: 9833520, unit: "km²", source: "US Census" },
  { text: "Area of Brazil", value: 8515767, unit: "km²", source: "IBGE" },
  { text: "Area of Australia", value: 7692024, unit: "km²", source: "Geoscience AU" },
  { text: "Area of India", value: 3287263, unit: "km²", source: "Survey of India" },
  { text: "Area of the Sahara Desert", value: 9200000, unit: "km²", source: "Britannica" },
  { text: "Area of the Amazon Rainforest", value: 5500000, unit: "km²", source: "WWF" },
  { text: "Area of the Moon's surface", value: 37900000, unit: "km²", source: "NASA" },
  { text: "Number of bones in the human body", value: 206, unit: "bones", source: "Gray's Anatomy" },
  { text: "Number of muscles in the human body", value: 600, unit: "muscles", source: "NIH" },
  { text: "Average heartbeats per day", value: 100000, unit: "beats", source: "AHA" },
  { text: "Number of breaths per day (average)", value: 22000, unit: "breaths", source: "EPA" },
  { text: "Length of human intestines", value: 7, unit: "meters", source: "NIH" },
  { text: "Number of neurons in the human brain", value: 86000000000, unit: "neurons", source: "NIH" },
  { text: "Cells in the human body", value: 37200000000000, unit: "cells", source: "NIH" },
  { text: "Average human walking speed", value: 5, unit: "km/h", source: "Various" },
  { text: "World record 100m sprint time", value: 9.58, unit: "seconds", source: "Usain Bolt 2009" },
  { text: "World record marathon time", value: 120, unit: "minutes", source: "Kelvin Kiptum 2023" },
  { text: "FIFA World Cup total goals scored (all time)", value: 2720, unit: "goals", source: "FIFA 2022" },
  { text: "NBA court length", value: 28.7, unit: "meters", source: "NBA" },
  { text: "Soccer field length (max)", value: 120, unit: "meters", source: "FIFA" },
  { text: "Olympic swimming pool length", value: 50, unit: "meters", source: "FINA" },
  { text: "Average temperature on Mars", value: -62, unit: "°C", source: "NASA" },
  { text: "Average temperature on Venus", value: 464, unit: "°C", source: "NASA" },
  { text: "Hottest temperature ever recorded on Earth", value: 56.7, unit: "°C", source: "Death Valley 1913" },
  { text: "Coldest temperature ever recorded on Earth", value: -89.2, unit: "°C", source: "Vostok 1983" },
  { text: "Boiling point of water", value: 100, unit: "°C", source: "Physics" },
  { text: "Melting point of iron", value: 1538, unit: "°C", source: "Chemistry" },
  { text: "Surface temperature of the Sun", value: 5500, unit: "°C", source: "NASA" },
  { text: "Age of the Earth", value: 4540000000, unit: "years", source: "USGS" },
  { text: "Age of the Universe", value: 13800000000, unit: "years", source: "NASA/Planck" },
  { text: "Years since dinosaurs went extinct", value: 66000000, unit: "years", source: "Paleontology" },
  { text: "Year the pyramids of Giza were built", value: 2560, unit: "BCE", source: "Archaeology" },
  { text: "Year the Roman Empire fell (Western)", value: 476, unit: "CE", source: "History" },
  { text: "Number of countries in the world", value: 195, unit: "countries", source: "UN" },
  { text: "Number of languages spoken in the world", value: 7168, unit: "languages", source: "Ethnologue 2024" },
  { text: "Number of islands in Indonesia", value: 17508, unit: "islands", source: "BIG Indonesia" },
  { text: "Number of islands in the Philippines", value: 7641, unit: "islands", source: "NAMRIA" },
  { text: "Number of letters in the English alphabet", value: 26, unit: "letters", source: "Common Knowledge" },
  { text: "Number of letters in the Hawaiian alphabet", value: 13, unit: "letters", source: "Linguistics" },
  { text: "Number of keys on a standard piano", value: 88, unit: "keys", source: "Music" },
  { text: "Number of cards in a standard deck", value: 52, unit: "cards", source: "Common Knowledge" },
  { text: "Number of chess pieces per player", value: 16, unit: "pieces", source: "FIDE" },
  { text: "Number of squares on a chess board", value: 64, unit: "squares", source: "FIDE" },
  { text: "Average lifespan of a housefly", value: 28, unit: "days", source: "Entomology" },
  { text: "Average lifespan of a tortoise", value: 100, unit: "years", source: "Zoology" },
  { text: "Average lifespan of a blue whale", value: 80, unit: "years", source: "NOAA" },
  { text: "Average lifespan of a honeybee (worker)", value: 42, unit: "days", source: "Entomology" },
  { text: "Average lifespan of an elephant", value: 70, unit: "years", source: "WWF" },
  { text: "Average lifespan of a goldfish", value: 10, unit: "years", source: "Ichthyology" },
  { text: "Top speed of a cheetah", value: 112, unit: "km/h", source: "Zoology" },
  { text: "Top speed of a peregrine falcon (diving)", value: 389, unit: "km/h", source: "Ornithology" },
  { text: "Top speed of a sailfish", value: 110, unit: "km/h", source: "Marine Biology" },
  { text: "Top speed of a house cat", value: 48, unit: "km/h", source: "Zoology" },
  { text: "Top speed of Usain Bolt", value: 44.72, unit: "km/h", source: "IAAF" },
  { text: "Top speed of a snail", value: 0.05, unit: "km/h", source: "Zoology" },
  { text: "Weight of a blue whale", value: 150000, unit: "kg", source: "NOAA" },
  { text: "Weight of an African elephant", value: 6000, unit: "kg", source: "WWF" },
  { text: "Weight of a hippopotamus", value: 1800, unit: "kg", source: "Zoology" },
  { text: "Weight of a polar bear", value: 450, unit: "kg", source: "WWF" },
  { text: "Weight of a kangaroo", value: 90, unit: "kg", source: "Zoology" },
  { text: "Weight of an average human", value: 70, unit: "kg", source: "WHO" },
  { text: "Number of stars in the Milky Way", value: 200000000000, unit: "stars", source: "NASA" },
  { text: "Number of galaxies in the observable universe", value: 2000000000000, unit: "galaxies", source: "NASA/Hubble" },
  { text: "Number of ants on Earth (estimated)", value: 20000000000000000, unit: "ants", source: "PNAS 2022" },
  { text: "Number of trees on Earth", value: 3040000000000, unit: "trees", source: "Nature 2015" },
  { text: "Number of fish in the ocean (estimated)", value: 3500000000000, unit: "fish", source: "Marine Biology" },
  { text: "Percentage of Earth covered by water", value: 71, unit: "%", source: "USGS" },
  { text: "Percentage of Earth's water that is freshwater", value: 3, unit: "%", source: "USGS" },
  { text: "Percentage of the ocean that has been explored", value: 5, unit: "%", source: "NOAA" },
  { text: "Annual revenue of Apple (2024)", value: 383000000000, unit: "USD", source: "Apple 10-K" },
  { text: "Annual revenue of Walmart (2024)", value: 648000000000, unit: "USD", source: "Walmart 10-K" },
  { text: "Annual revenue of Amazon (2024)", value: 575000000000, unit: "USD", source: "Amazon 10-K" },
  { text: "Annual revenue of Toyota (2024)", value: 275000000000, unit: "USD", source: "Toyota" },
  { text: "GDP of the United States (2024)", value: 28800000000000, unit: "USD", source: "World Bank" },
  { text: "GDP of China (2024)", value: 18500000000000, unit: "USD", source: "World Bank" },
  { text: "GDP of Japan (2024)", value: 4200000000000, unit: "USD", source: "World Bank" },
  { text: "GDP of Germany (2024)", value: 4500000000000, unit: "USD", source: "World Bank" },
  { text: "GDP of India (2024)", value: 3900000000000, unit: "USD", source: "World Bank" },
  { text: "GDP of the United Kingdom (2024)", value: 3500000000000, unit: "USD", source: "World Bank" },
  { text: "Average salary in the United States (2024)", value: 63795, unit: "USD/year", source: "BLS" },
  { text: "Average salary in Switzerland (2024)", value: 96000, unit: "USD/year", source: "OECD" },
  { text: "Average salary in India (2024)", value: 8700, unit: "USD/year", source: "World Bank" },
  { text: "Average salary in Japan (2024)", value: 41500, unit: "USD/year", source: "OECD" },
  { text: "Price of a Big Mac in the US (2024)", value: 5.69, unit: "USD", source: "Economist Big Mac Index" },
  { text: "Price of a Big Mac in Switzerland (2024)", value: 7.73, unit: "USD", source: "Economist Big Mac Index" },
  { text: "Price of a Big Mac in India (2024)", value: 2.33, unit: "USD", source: "Economist Big Mac Index" },
  { text: "Number of McDonald's restaurants worldwide", value: 40275, unit: "restaurants", source: "McDonald's 2023" },
  { text: "Number of Starbucks stores worldwide", value: 38587, unit: "stores", source: "Starbucks 2024" },
  { text: "Number of Subway restaurants worldwide", value: 37000, unit: "restaurants", source: "Subway 2024" },
  { text: "Daily Google searches", value: 8500000000, unit: "searches", source: "Google/Statista" },
  { text: "Monthly active users of Facebook", value: 3050000000, unit: "users", source: "Meta Q4 2023" },
  { text: "Monthly active users of Instagram", value: 2000000000, unit: "users", source: "Meta 2023" },
  { text: "Monthly active users of TikTok", value: 1500000000, unit: "users", source: "ByteDance 2023" },
  { text: "Monthly active users of Twitter/X", value: 550000000, unit: "users", source: "X 2024" },
  { text: "Monthly active users of Reddit", value: 430000000, unit: "users", source: "Reddit 2023" },
  { text: "Number of songs on Spotify", value: 100000000, unit: "songs", source: "Spotify 2024" },
  { text: "Number of Netflix subscribers worldwide", value: 283000000, unit: "subscribers", source: "Netflix Q4 2024" },
  { text: "Number of iPhones sold (2024)", value: 235000000, unit: "phones", source: "IDC" },
  { text: "Number of websites on the internet", value: 1130000000, unit: "websites", source: "Netcraft 2024" },
  { text: "Number of emails sent per day globally", value: 347000000000, unit: "emails", source: "Statista 2024" },
  { text: "Hours of video uploaded to YouTube per minute", value: 500, unit: "hours", source: "YouTube" },
  { text: "Calories in an avocado", value: 240, unit: "calories", source: "USDA" },
  { text: "Calories in a banana", value: 105, unit: "calories", source: "USDA" },
  { text: "Calories in a slice of pizza", value: 285, unit: "calories", source: "USDA" },
  { text: "Calories in a glazed donut", value: 253, unit: "calories", source: "USDA" },
  { text: "Caffeine in a cup of coffee (8oz)", value: 95, unit: "mg", source: "FDA" },
  { text: "Caffeine in a can of Red Bull", value: 80, unit: "mg", source: "Red Bull" },
  { text: "Caffeine in a cup of green tea", value: 28, unit: "mg", source: "USDA" },
  { text: "Water in a watermelon (percentage)", value: 92, unit: "%", source: "USDA" },
  { text: "Water in a cucumber (percentage)", value: 96, unit: "%", source: "USDA" },
  { text: "Passengers on the Titanic", value: 2224, unit: "people", source: "History" },
  { text: "Survivors of the Titanic", value: 710, unit: "people", source: "History" },
  { text: "Year the Titanic sank", value: 1912, unit: "CE", source: "History" },
  { text: "Year humans first walked on the Moon", value: 1969, unit: "CE", source: "NASA" },
  { text: "Year the Berlin Wall fell", value: 1989, unit: "CE", source: "History" },
  { text: "Year the internet was invented (ARPANET)", value: 1969, unit: "CE", source: "DARPA" },
  { text: "Year the first iPhone was released", value: 2007, unit: "CE", source: "Apple" },
  { text: "Year Wikipedia was launched", value: 2001, unit: "CE", source: "Wikimedia" },
  { text: "Number of words in the Harry Potter series", value: 1084170, unit: "words", source: "Scholastic" },
  { text: "Number of words in the Lord of the Rings", value: 576459, unit: "words", source: "HarperCollins" },
  { text: "Number of words in the Bible (King James)", value: 783137, unit: "words", source: "Various" },
  { text: "Number of episodes of The Simpsons", value: 768, unit: "episodes", source: "Fox (through 2024)" },
  { text: "Number of James Bond films", value: 25, unit: "films", source: "EON Productions" },
  { text: "Number of Marvel Cinematic Universe films", value: 34, unit: "films", source: "Marvel Studios 2024" },
  { text: "Box office revenue of Avatar (2009)", value: 2923000000, unit: "USD", source: "Box Office Mojo" },
  { text: "Box office revenue of Titanic (1997)", value: 2264000000, unit: "USD", source: "Box Office Mojo" },
  { text: "Box office revenue of The Avengers: Endgame", value: 2799000000, unit: "USD", source: "Box Office Mojo" },
  { text: "Cost to build the International Space Station", value: 150000000000, unit: "USD", source: "NASA" },
  { text: "Cost to build the Panama Canal", value: 500000000, unit: "USD (1914)", source: "History" },
  { text: "Cost to build the Golden Gate Bridge", value: 35000000, unit: "USD (1937)", source: "GGB District" },
  { text: "Wingspan of a Boeing 747", value: 64.4, unit: "meters", source: "Boeing" },
  { text: "Wingspan of an albatross", value: 3.5, unit: "meters", source: "Ornithology" },
  { text: "Length of a football field (American)", value: 109.7, unit: "meters", source: "NFL" },
  { text: "Length of a tennis court", value: 23.77, unit: "meters", source: "ITF" },
  { text: "Volume of Lake Baikal", value: 23615, unit: "km³", source: "Russian Academy" },
  { text: "Volume of Lake Superior", value: 12100, unit: "km³", source: "NOAA" },
  { text: "Volume of water in all Earth's oceans", value: 1335000000, unit: "km³", source: "NOAA" },
  { text: "Annual CO2 emissions worldwide (2023)", value: 37400000000, unit: "tonnes", source: "Global Carbon Project" },
  { text: "Number of species discovered on Earth", value: 8700000, unit: "species", source: "UNEP" },
  { text: "Number of dog breeds recognized by AKC", value: 200, unit: "breeds", source: "AKC 2024" },
  { text: "Number of cat breeds recognized by CFA", value: 45, unit: "breeds", source: "CFA 2024" },
  { text: "Average IQ score", value: 100, unit: "points", source: "Psychology" },
  { text: "Number of time zones in the world", value: 24, unit: "time zones", source: "Geography" },
  { text: "Number of US states", value: 50, unit: "states", source: "US Government" },
  { text: "Number of teeth in an adult human", value: 32, unit: "teeth", source: "ADA" },
  { text: "Number of chromosomes in a human cell", value: 46, unit: "chromosomes", source: "NIH" },
  { text: "Percentage of DNA shared with chimpanzees", value: 98.7, unit: "%", source: "NIH" },
  { text: "Percentage of DNA shared with bananas", value: 60, unit: "%", source: "NIH" },
  { text: "Average rainfall in the Amazon per year", value: 2300, unit: "mm", source: "INPE" },
  { text: "Average rainfall in the Sahara per year", value: 25, unit: "mm", source: "Meteorology" },
  { text: "Average rainfall in London per year", value: 602, unit: "mm", source: "Met Office" },
  { text: "Average rainfall in Seattle per year", value: 952, unit: "mm", source: "NWS" },
  { text: "Number of Olympic sports (Summer 2024)", value: 32, unit: "sports", source: "IOC" },
  { text: "Countries that have hosted the Olympics", value: 23, unit: "countries", source: "IOC" },
  { text: "Most Olympic gold medals (individual)", value: 23, unit: "gold medals", source: "Michael Phelps" },
  { text: "Number of Grand Slam tennis titles (Djokovic)", value: 24, unit: "titles", source: "ATP 2024" },
  { text: "Most goals in FIFA World Cup history (individual)", value: 16, unit: "goals", source: "Miroslav Klose" },
  { text: "Capacity of the largest stadium (Narendra Modi)", value: 132000, unit: "seats", source: "GCA" },
  { text: "Capacity of Wembley Stadium", value: 90000, unit: "seats", source: "FA" },
  { text: "Capacity of Madison Square Garden", value: 20789, unit: "seats", source: "MSG" },
  { text: "Top speed of a Formula 1 car", value: 372, unit: "km/h", source: "FIA" },
  { text: "Top speed of a commercial airplane", value: 945, unit: "km/h", source: "Boeing 747" },
  { text: "Top speed of the fastest train (maglev)", value: 603, unit: "km/h", source: "JR Central" },
  { text: "Top speed of a Tesla Model S Plaid", value: 322, unit: "km/h", source: "Tesla" },
  { text: "Year coffee was first discovered", value: 850, unit: "CE", source: "History (Ethiopia)" },
  { text: "Year chocolate was first consumed", value: 1900, unit: "BCE", source: "Archaeology (Mesoamerica)" },
  { text: "Year pizza margherita was invented", value: 1889, unit: "CE", source: "History (Naples)" },
  { text: "Annual production of bananas worldwide", value: 124000000, unit: "tonnes", source: "FAO 2023" },
  { text: "Annual production of coffee worldwide", value: 10500000, unit: "tonnes", source: "ICO 2023" },
  { text: "Annual production of rice worldwide", value: 520000000, unit: "tonnes", source: "FAO 2023" },
  { text: "Annual production of steel worldwide", value: 1888000000, unit: "tonnes", source: "World Steel 2023" },
  { text: "Amount of gold ever mined in history", value: 212582, unit: "tonnes", source: "World Gold Council" },
  { text: "Daily oil production worldwide", value: 101800000, unit: "barrels/day", source: "EIA 2024" },
  { text: "Percentage of electricity from renewables (global)", value: 30, unit: "%", source: "IEA 2023" },
  { text: "Number of nuclear power plants worldwide", value: 440, unit: "plants", source: "IAEA 2024" },
  { text: "Tallest tree in the world (Hyperion)", value: 116, unit: "meters", source: "NPS" },
  { text: "Oldest tree in the world (Methuselah)", value: 4856, unit: "years old", source: "USFS" },
  { text: "Largest flower in the world (Rafflesia)", value: 1, unit: "meter diameter", source: "Botany" },
  { text: "Number of taste buds on a human tongue", value: 10000, unit: "taste buds", source: "NIH" },
  { text: "Number of scent receptors in a dog's nose", value: 300000000, unit: "receptors", source: "Zoology" },
  { text: "Wingbeats per second of a hummingbird", value: 80, unit: "beats/sec", source: "Ornithology" },
  { text: "Wingbeats per second of a mosquito", value: 600, unit: "beats/sec", source: "Entomology" },
  { text: "Number of Wikipedia articles (English)", value: 6800000, unit: "articles", source: "Wikimedia 2024" },
  { text: "Number of books in the Library of Congress", value: 17000000, unit: "books", source: "LOC" },
  { text: "Number of photos uploaded to Instagram per day", value: 100000000, unit: "photos", source: "Meta" },
  { text: "Number of tweets sent per day", value: 500000000, unit: "tweets", source: "X/Twitter" },
  { text: "Electricity used by Bitcoin mining per year", value: 150, unit: "TWh", source: "Cambridge" },
  { text: "Total electricity generated worldwide per year", value: 29165, unit: "TWh", source: "IEA 2023" },
  { text: "Internet users worldwide", value: 5440000000, unit: "users", source: "ITU 2024" },
  { text: "Smartphone users worldwide", value: 4880000000, unit: "users", source: "Statista 2024" },
  { text: "Data created per day globally", value: 402000000, unit: "terabytes", source: "Statista 2024" },
  { text: "Cost of the Apollo program (adjusted)", value: 257000000000, unit: "USD (2023)", source: "NASA/PSI" },
  { text: "US national debt (2024)", value: 34000000000000, unit: "USD", source: "US Treasury" },
  { text: "Value of all Bitcoin (2024)", value: 1300000000000, unit: "USD", source: "CoinMarketCap" },
  { text: "Annual US military budget (2024)", value: 886000000000, unit: "USD", source: "DoD" },
  { text: "Annual US education spending", value: 860000000000, unit: "USD", source: "NCES" },
  { text: "Annual NASA budget (2024)", value: 25000000000, unit: "USD", source: "NASA" },
  { text: "Cost of a Space Shuttle launch", value: 450000000, unit: "USD", source: "NASA" },
  { text: "Cost of a SpaceX Falcon 9 launch", value: 67000000, unit: "USD", source: "SpaceX" },
  { text: "Number of people who have been to space", value: 676, unit: "people", source: "FAI 2024" },
  { text: "Number of people who have walked on the Moon", value: 12, unit: "people", source: "NASA" },
  { text: "Passengers carried by airlines per year", value: 4700000000, unit: "passengers", source: "IATA 2024" },
  { text: "Number of airports in the world", value: 41820, unit: "airports", source: "CIA Factbook" },
  { text: "Busiest airport by passengers (Atlanta)", value: 93700000, unit: "passengers/year", source: "ACI 2023" },
  { text: "Length of the longest commercial flight (SIN-JFK)", value: 18, unit: "hours", source: "Singapore Airlines" },
  { text: "Number of cars produced per year globally", value: 67000000, unit: "cars", source: "OICA 2023" },
  { text: "Number of bicycles in the Netherlands per capita", value: 1.3, unit: "bikes per person", source: "CBS" },
  { text: "Average commute time in the US", value: 27.6, unit: "minutes", source: "US Census" },
  { text: "Average commute time in Tokyo", value: 48, unit: "minutes", source: "NHK" },
  { text: "Percentage of the workforce working remotely (US)", value: 28, unit: "%", source: "Pew 2024" }
];
